version: 0.0
os: linux
files:
  - source: / # This represents the root of the source bundle
    destination: /var/www/html/ # This is where files will be placed on the EC2 instance

hooks:
  ApplicationStop:
    - location: scripts/stop_apache.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_apache.sh
      timeout: 300
      runas: root
